#!/usr/bin/env python3
"""
Draws logos/src/glyphs/football.svg.

    python3 tools/draw/football.py

A football: the silhouette as a ring, one pentagon at the centre and five at
the rim. The pattern is regular, so it is computed rather than typed - change
the five numbers below and re-run.

Note what this glyph does NOT do. The other two committee glyphs are solid
masses with their detail cut out as evenodd holes, because their detail sits
INSIDE the mass and a lighter tone would drop out of the one-ink variants.
Here the patches are separate shapes in the same ink, so they simply union and
no hole is needed - and unioning is what we want, since the rim patches have
to merge into the silhouette the way they do on a real ball. Separate elements
may overlap freely; only subpaths of one evenodd path cancel.

The patches are also kept the darker element, with the ball's body left open.
That is the way round a real football reads. Inverted - a solid disc with
light pentagons - it still reads as a ball, but as a photographic negative of
one, and it goes muddy at 28 px.
"""
import math, os

def poly(cx, cy, R, rot_deg, n=5):
    pts = [(cx + R*math.cos(math.radians(rot_deg + 360*i/n)),
            cy + R*math.sin(math.radians(rot_deg + 360*i/n))) for i in range(n)]
    return "M " + " L ".join(f"{x:.2f},{y:.2f}" for x, y in pts) + " Z"

CX = CY = 50.0
RING, SW  = 40.0, 5.5     # silhouette: radius and stroke width
RC        = 12.5          # centre pentagon, circumradius
RO, DO    = 12.0, 29.0    # rim pentagons: circumradius, and distance from centre.
                          # RO + DO overshoots RING on purpose, so each rim patch
                          # runs into the silhouette instead of floating inside it.

INK = 'var(--glyph, #b0643e)'
parts = [f'<circle cx="{CX:g}" cy="{CY:g}" r="{RING:g}" fill="none" stroke="{INK}" stroke-width="{SW:g}"/>',
         f'<path fill="{INK}" d="{poly(CX, CY, RC, -90)}"/>']
for k in range(5):
    a = -90 + 72*k
    parts.append(f'<path fill="{INK}" d="'
                 + poly(CX + DO*math.cos(math.radians(a)), CY + DO*math.sin(math.radians(a)), RO, a)
                 + '"/>')

out = os.path.join(os.path.dirname(__file__), "..", "..", "logos", "src", "glyphs", "football.svg")
open(out, "w").write(
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">\n'
    '  <title>Comité des sports — اللجنة الرياضية</title>\n'
    '  <!-- GENERATED by tools/draw/football.py. Do not hand-edit the coordinates. -->\n  '
    + "\n  ".join(parts) + "\n</svg>\n")
print("wrote", os.path.relpath(out))
