#!/usr/bin/env python3
"""
Draws the eight Mayor's Cup team crests into logos/src/teams/mayor-cup-2026/.

    python3 tools/draw/mayor-cup-teams.py

FILED BY EDITION, not by club. The eight names are this year's entrants and the
next Mayor's Cup will not have the same eight — a club folds, two merge, a new
one enters — so a crest belongs to an edition the way a fixture does. Filing
them flat under teams/ would make next August's set either overwrite this one
or collide with it. EVENT below is the only thing to change for a new edition;
it matches the event id in brand/entities.yml so the two trees line up.

These are STANDALONE marks. A committee wears the mosque and an event carries
the association's endorsement; a team is a competitor, not the association
acting in a field, so it gets none of that — no symbol, no endorsement, no
wordmark bound by the engine. That is also why the colours are literal here
rather than var() bound: nothing downstream re-inks these, so a token that no
build resolves would be a lie. The VALUES still come from the palette, listed
once in PALETTE below, so the set stays in the family by construction.

The visual language is taken from the eight crests the U18 clubs made
themselves (resources/u18-team-*.webp): a shield with a bright metal edge, a
dark field, an emblem keyed to what the club's NAME MEANS, and a football. Six
of those eight are shields and two are medallions, so both shapes are kept.
What is not kept is how they were made — four are AI renders with a stadium or
a leather ball baked into the background, which is why they cannot be put on a
fixture card. These are flat vector on a transparent ground.

The emblem is the part that carries the club. Each is a reading of the name:

    الناجحين   the successful   a summit, and the star above it
    الشناقطة   of Chinguetti    the minaret of the old town, over an open book
    لبنان      Lebanon          the cedar
    الصادقين   the truthful     an eight-point star, true in every direction
    أفجار      the dawns        the sun coming up over two dune ridges
    الذهبيين   the golden       a sun disc inside a laurel
    البارين    the dutiful      two ears of wheat, what duty yields
    الحزام     the belt         the belt itself, worn across the shield

── two things that were wrong in the first pass, and why they are structural ──

EVERYTHING IS CLIPPED TO THE SHIELD. The belt is a band 380 units long crossed
over a shield 348 wide; unclipped it hangs off both edges as a plank. Clipping
is not a safety net here, it is how a bend is drawn — the band is MEANT to run
edge to edge and stop at the outline. Every other emblem is clipped by the same
group, so no emblem can ever escape its crest no matter how it is retuned.

THE BALL IS FIVE SEAMS, NOT SIX PENTAGONS. logos/src/glyphs/football.svg is a
ring carrying six pentagons, and it is right at the size a glyph is used. Put
at r=50 inside a crest it stops being a ball: the five rim pentagons read as
separate blobs and the whole thing goes to a gear. What survives at crest scale
is the simplest true statement of a football — one pentagon at the centre and a
seam from each of its vertices to the rim. That is drawn here instead.
"""
import math
import os

MARK = "GENERATED by tools/draw/mayor-cup-teams.py"
EVENT = "mayor-cup-2026"       # the edition these eight belong to
W = 512.0                      # the box every crest is drawn in
CX = 256.0

# ── palette ──────────────────────────────────────────────────────────────────
# Values copied from brand/tokens/color.json. Copied rather than read because
# this script writes standalone artwork that the token build never touches; a
# JSON dependency here would imply a binding that does not exist.
FIELD = "#10271f"              # palette.mint.900 — the ground under every crest
CREAM = "#f7f3ee"              # palette.cream.base

ACCENTS = {
    "azure":    ("#3a6ea5", "#dbe7f3"),
    "copper":   ("#b0643e", "#f2e0d4"),
    "clinical": ("#2f8f7d", "#d9efea"),
    "plum":     ("#7a4b6e", "#ecdfe9"),
    "sand":     ("#9a8558", "#efe9db"),
    # Three the palette does not carry yet. A league needs eight legible strips
    # and the registry has six accents, one of which (saffron) the Mayor's Cup
    # itself owns and does not share. Tuned the same way as the others: mid
    # chroma, so none of them fights mint when the eight sit in a group table.
    "garnet":   ("#9c3548", "#f0dade"),
    "olive":    ("#6e7a3c", "#e8ecd8"),
    "slate":    ("#4f6472", "#dfe6ea"),
}


def f(x):
    """Coordinates at 2dp. Full float repr triples the file size and no one can
    read a diff of it."""
    return f"{x:.2f}"


# ── shield silhouettes ───────────────────────────────────────────────────────
# Each takes an INSET and returns a closed path, so the keyline is a genuinely
# smaller shield rather than a scaled copy of the outline. Scaling about a
# fixed point was the first attempt and it drifts: a shield is not radially
# symmetric, so a uniform scale pulls the keyline tight against the point and
# leaves it slack under the top edge.
#
# They share one skeleton — a top edge, two sides that run straight and then
# sweep to a point — and differ only in the top edge and the sweep. `waist` is
# where the straight run ends as a fraction of the height, `tuck` how far in
# the control points sit: a low tuck gives a long point, a high one a shovel.

def _sides(cx, top, bot, half, waist, tuck):
    h = bot - top
    ys = top + waist * h
    y1 = top + (waist + (1 - waist) * 0.55) * h
    return (
        f"L {f(cx + half)},{f(ys)} "
        f"C {f(cx + half)},{f(y1)} {f(cx + half * tuck)},{f(bot - h * 0.02)} {f(cx)},{f(bot)} "
        f"C {f(cx - half * tuck)},{f(bot - h * 0.02)} {f(cx - half)},{f(y1)} {f(cx - half)},{f(ys)} "
    )


def heater(d=0.0, top=62, bot=458, half=172, waist=0.44, tuck=0.62, r=22):
    """The classic. A flat top with rounded corners."""
    top, bot, half = top + d, bot - d * 0.9, half - d
    return (
        f"M {f(CX - half)},{f(top + r)} "
        f"Q {f(CX - half)},{f(top)} {f(CX - half + r)},{f(top)} "
        f"L {f(CX + half - r)},{f(top)} "
        f"Q {f(CX + half)},{f(top)} {f(CX + half)},{f(top + r)} "
        + _sides(CX, top, bot, half, waist, tuck) + "Z"
    )


def peaked(d=0.0, top=60, bot=456, half=172, rise=30.0, waist=0.44, tuck=0.62):
    """A shallow peak at the centre of the top edge."""
    top, bot, half = top + d, bot - d * 0.9, half - d
    return (
        f"M {f(CX - half)},{f(top + rise)} "
        f"L {f(CX)},{f(top)} L {f(CX + half)},{f(top + rise)} "
        + _sides(CX, top + rise, bot, half, waist, tuck) + "Z"
    )


def arched(d=0.0, top=52, bot=456, half=170, spring=96.0, waist=0.40, tuck=0.60):
    """A two-centred pointed arch — the shape over a mosque door."""
    top, bot, half = top + d, bot - d * 0.9, half - d
    return (
        f"M {f(CX - half)},{f(top + spring)} "
        f"C {f(CX - half)},{f(top + spring * 0.30)} {f(CX - half * 0.46)},{f(top)} {f(CX)},{f(top)} "
        f"C {f(CX + half * 0.46)},{f(top)} {f(CX + half)},{f(top + spring * 0.30)} "
        f"{f(CX + half)},{f(top + spring)} "
        + _sides(CX, top + spring, bot, half, waist, tuck) + "Z"
    )


def domed(d=0.0, top=56, bot=458, half=168, waist=0.44, tuck=0.62):
    """A semicircular top."""
    top, bot, half = top + d, bot - d * 0.9, half - d
    return (
        f"M {f(CX - half)},{f(top + half)} "
        f"A {f(half)},{f(half)} 0 0 1 {f(CX + half)},{f(top + half)} "
        + _sides(CX, top + half, bot, half, waist, tuck) + "Z"
    )


def notched(d=0.0, top=62, bot=456, half=172, notch=34.0, waist=0.44, tuck=0.62):
    """A flat top interrupted by a V cut into it — the chief indented."""
    top, bot, half = top + d, bot - d * 0.9, half - d
    return (
        f"M {f(CX - half)},{f(top)} "
        f"L {f(CX - notch)},{f(top)} L {f(CX)},{f(top + notch * 0.85)} "
        f"L {f(CX + notch)},{f(top)} L {f(CX + half)},{f(top)} "
        + _sides(CX, top, bot, half, waist, tuck) + "Z"
    )


# ── primitives ───────────────────────────────────────────────────────────────

def path(d, fill=None, stroke=None, width=None, cap="round", join="round"):
    a = [f'fill="{fill}"' if fill else 'fill="none"']
    if stroke:
        a += [f'stroke="{stroke}"', f'stroke-width="{f(width)}"',
              f'stroke-linecap="{cap}"', f'stroke-linejoin="{join}"']
    a.append(f'd="{d}"')
    return "  <path " + " ".join(a) + "/>"


def poly(pts, **kw):
    return path("M " + " L ".join(f"{f(x)},{f(y)}" for x, y in pts) + " Z", **kw)


def line(a, b, **kw):
    return path(f"M {f(a[0])},{f(a[1])} L {f(b[0])},{f(b[1])}", **kw)


def circle(cx, cy, r, fill=None, stroke=None, width=None):
    a = [f'fill="{fill}"' if fill else 'fill="none"']
    if stroke:
        a += [f'stroke="{stroke}"', f'stroke-width="{f(width)}"']
    a.append(f'cx="{f(cx)}" cy="{f(cy)}" r="{f(r)}"')
    return "  <circle " + " ".join(a) + "/>"


def ngon(cx, cy, r, n, rot=-90.0):
    return [(cx + r * math.cos(math.radians(rot + k * 360.0 / n)),
             cy + r * math.sin(math.radians(rot + k * 360.0 / n))) for k in range(n)]


def star_pts(cx, cy, ro, ri, n=5, rot=-90.0):
    pts = []
    for k in range(n * 2):
        r = ro if k % 2 == 0 else ri
        a = math.radians(rot + k * 180.0 / n)
        pts.append((cx + r * math.cos(a), cy + r * math.sin(a)))
    return pts


def football(cx, cy, r, dark, light):
    """A ball as one pentagon and five seams. See the header for why this is not
    the six-pentagon glyph."""
    pent = ngon(cx, cy, r * 0.40, 5)
    out = [circle(cx, cy, r, fill=light), poly(pent, fill=dark)]
    for vx, vy in pent:                       # a seam out of every vertex
        a = math.atan2(vy - cy, vx - cx)
        out.append(line((vx, vy), (cx + r * math.cos(a), cy + r * math.sin(a)),
                        stroke=dark, width=r * 0.15))
    out.append(circle(cx, cy, r - r * 0.05, stroke=dark, width=r * 0.10))
    return out


# ── emblems ──────────────────────────────────────────────────────────────────
# Each takes the centre of its zone and returns a list of elements. `ink` is
# the light that reads against the dark field and carries the silhouette; `hi`
# is the club's accent and is only ever added detail — an emblem must still be
# itself with every `hi` part removed.

def em_summit(cx, cy, ink, hi):
    """الناجحين — a summit, and the star that sits over it."""
    return [
        poly(star_pts(cx, cy - 96, 38, 16), fill=hi),
        poly([(cx - 112, cy + 56), (cx - 40, cy - 50), (cx + 2, cy + 8),
              (cx + 30, cy - 26), (cx + 112, cy + 56)], fill=ink),
        poly([(cx - 40, cy - 50), (cx - 12, cy - 8), (cx - 68, cy - 8)], fill=hi),
    ]


def em_minaret(cx, cy, ink, hi):
    """الشناقطة — Chinguetti's square stone minaret, over an open book.

    Chinguetti's tower is STOUT: a broad square shaft barely three times its own
    width, with a wide parapet. Drawn tall and narrow it stops being that tower
    and becomes a lighthouse, which is what the first pass drew."""
    base = cy + 30
    out = [
        poly([(cx - 46, base), (cx - 36, cy - 66), (cx + 36, cy - 66), (cx + 46, base)], fill=ink),
        poly([(cx - 25, cy - 66), (cx - 21, cy - 112), (cx + 21, cy - 112), (cx + 25, cy - 66)],
             fill=ink),                                    # the lantern
        poly([(cx - 27, cy - 112), (cx, cy - 146), (cx + 27, cy - 112)], fill=hi),
    ]
    # Arrow slits, drawn VERTICALLY. Horizontal courses were the first attempt
    # and they slice the shaft into a stack of discs — the tower stops being a
    # tower and becomes a pile of pancakes. A vertical opening does the opposite:
    # it is the one mark that says "this thing is upright".
    for dx in (-19, 19):
        out.append(line((cx + dx, cy - 44), (cx + dx, cy + 6), stroke=FIELD, width=10))
    out.append(line((cx, cy - 100), (cx, cy - 80), stroke=FIELD, width=8))
    # the book: two leaves off a spine, wide enough to be a base for the tower
    out += [
        path(f"M {f(cx)},{f(base + 12)} C {f(cx - 34)},{f(base - 6)} {f(cx - 78)},{f(base - 8)} "
             f"{f(cx - 116)},{f(base + 2)} L {f(cx - 116)},{f(base + 58)} "
             f"C {f(cx - 78)},{f(base + 48)} {f(cx - 34)},{f(base + 50)} {f(cx)},{f(base + 70)} Z",
             fill=ink),
        path(f"M {f(cx)},{f(base + 12)} C {f(cx + 34)},{f(base - 6)} {f(cx + 78)},{f(base - 8)} "
             f"{f(cx + 116)},{f(base + 2)} L {f(cx + 116)},{f(base + 58)} "
             f"C {f(cx + 78)},{f(base + 48)} {f(cx + 34)},{f(base + 50)} {f(cx)},{f(base + 70)} Z",
             fill=ink),
        line((cx, base + 14), (cx, base + 68), stroke=hi, width=8),
    ]
    return out


def em_cedar(cx, cy, ink, hi):
    """لبنان — the cedar.

    A cedar is not a fir, and the whole difference is the aspect ratio of a
    tier: a fir's tiers are as tall as they are wide and come to a spire, a
    cedar's are three times wider than tall and the top is FLAT. Drawing it
    with a spire — the first pass — gets a Christmas tree every time. Each tier
    here is a wide lozenge with a level top and a notched underside."""
    out = []
    for half, y, h in ((62, cy - 56, 26), (100, cy - 12, 30), (132, cy + 36, 34)):
        out.append(poly([
            (cx - half, y), (cx - half * 0.62, y - h * 0.66), (cx - half * 0.22, y - h * 0.34),
            (cx, y - h * 0.90), (cx + half * 0.22, y - h * 0.34), (cx + half * 0.62, y - h * 0.66),
            (cx + half, y),
            (cx + half * 0.58, y + h * 0.72), (cx + half * 0.20, y + h * 0.30),
            (cx, y + h * 0.86), (cx - half * 0.20, y + h * 0.30), (cx - half * 0.58, y + h * 0.72),
        ], fill=ink))
    out.append(poly([(cx - 14, cy + 44), (cx + 14, cy + 44),
                     (cx + 21, cy + 104), (cx - 21, cy + 104)], fill=hi))
    return out


def em_true_star(cx, cy, ink, hi):
    """الصادقين — eight points, the same in every direction. One star, not two:
    two rotated stars over each other read as a snowflake."""
    return [
        poly(star_pts(cx, cy, 116, 44, n=8, rot=-90), fill=ink),
        circle(cx, cy, 40, fill=FIELD),
        circle(cx, cy, 40, stroke=hi, width=9),
        poly(star_pts(cx, cy, 26, 11, n=5), fill=hi),
    ]


def em_dawn(cx, cy, ink, hi):
    """أفجار — the sun coming up behind two dune ridges.

    The dunes are RIDGE LINES, not filled bodies. Filled, the two of them are a
    pale slab across the bottom third of the shield with a bite out of it, and
    the sun has nothing to rise behind."""
    out = [circle(cx, cy, 68, fill=hi)]
    for k in range(9):                         # rays, over the top half only
        a = math.radians(190 + k * 20)
        out.append(line((cx + 80 * math.cos(a), cy + 80 * math.sin(a)),
                        (cx + 108 * math.cos(a), cy + 108 * math.sin(a)),
                        stroke=hi, width=10))
    # The dunes run OFF THE BOTTOM of the shield and are cut by the clip. Closed
    # on a baseline inside the field, as they were first drawn, they float: the
    # straight closing edge shows as a hard horizontal and the pair reads as a
    # cloud hanging in the middle of the crest rather than as ground.
    foot = cy + 330
    out += [
        path(f"M {f(cx - 230)},{f(foot)} C {f(cx - 130)},{f(cy + 140)} {f(cx + 30)},{f(cy + 152)} "
             f"{f(cx + 230)},{f(foot)} Z", fill=ink),
        path(f"M {f(cx + 20)},{f(foot)} C {f(cx + 96)},{f(cy + 186)} {f(cx + 150)},{f(cy + 198)} "
             f"{f(cx + 240)},{f(foot)} Z", fill=hi),
    ]
    return out


def em_sun_laurel(cx, cy, ink, hi):
    """الذهبيين — a sun disc held in a laurel."""
    out = [circle(cx, cy, 52, fill=hi)]
    for k in range(12):
        a = math.radians(k * 30)
        out.append(line((cx + 64 * math.cos(a), cy + 64 * math.sin(a)),
                        (cx + 88 * math.cos(a), cy + 88 * math.sin(a)), stroke=hi, width=11))
    for s in (-1, 1):
        out.append(path(
            f"M {f(cx + s * 112)},{f(cy + 96)} C {f(cx + s * 146)},{f(cy + 30)} "
            f"{f(cx + s * 132)},{f(cy - 50)} {f(cx + s * 80)},{f(cy - 100)}",
            stroke=ink, width=10))
        for k in range(5):
            t = k / 4.0
            lx = cx + s * (112 + 28 * math.sin(t * 3.1) - 36 * t * t)
            ly = cy + 96 - 198 * t
            out.append(path(
                f"M {f(lx)},{f(ly)} C {f(lx + s * 32)},{f(ly - 15)} "
                f"{f(lx + s * 36)},{f(ly - 38)} {f(lx + s * 11)},{f(ly - 45)} "
                f"C {f(lx + s * 7)},{f(ly - 24)} {f(lx + s * 2)},{f(ly - 11)} {f(lx)},{f(ly)} Z",
                fill=ink))
    return out


def em_palm(cx, cy, ink, hi):
    """البارين — a date palm.

    This was a wheat ear for three passes and a wheat ear will not draw at this
    size: the grains are the only thing that distinguishes it, and whatever they
    are made of — separate shapes, straight notches, scallops — they resolve at
    crest scale into a bead string, a lightning bolt or a coiled spring. A palm
    has the opposite property. It is a handful of long tapered fronds off one
    point, every one of which stays legible as it shrinks, and it is what
    actually grows here."""
    crown = cy - 24
    out = []
    for k in range(7):                          # the fronds, fanned from the crown
        a = math.radians(-195 + k * 35)
        # A frond ARCHES before it droops, so its midpoint sits nearer vertical
        # than its tip does. Running the midpoint along the same ray as the tip
        # makes every frond a straight lens and the crown reads as a dragonfly.
        am = a + math.radians(20 if a < math.radians(-90) else -20)
        tx, ty = cx + 108 * math.cos(a), crown + 100 * math.sin(a)
        mx, my = cx + 62 * math.cos(am), crown + 58 * math.sin(am)
        out.append(path(
            f"M {f(cx)},{f(crown)} "
            f"C {f(mx)},{f(my - 20)} {f(tx * 0.72 + mx * 0.28)},{f(ty - 30)} {f(tx)},{f(ty)} "
            f"C {f(tx * 0.60 + mx * 0.40)},{f(ty + 6)} {f(mx)},{f(my + 24)} {f(cx)},{f(crown)} Z",
            fill=ink))
    for dx, dy in ((-30, 18), (30, 18), (0, 34)):   # the dates
        out.append(circle(cx + dx, crown + dy, 11, fill=hi))
    out.append(path(                            # the trunk, leaning a little
        f"M {f(cx - 14)},{f(cy + 98)} C {f(cx - 8)},{f(cy + 48)} {f(cx - 6)},{f(cy + 14)} "
        f"{f(cx - 9)},{f(crown + 10)} L {f(cx + 9)},{f(crown + 10)} "
        f"C {f(cx + 8)},{f(cy + 14)} {f(cx + 12)},{f(cy + 48)} {f(cx + 18)},{f(cy + 98)} Z",
        fill=hi))
    return out


def em_belt(cx, cy, ink, hi):
    """الحزام — the belt, worn across the shield.

    Runs edge to edge and is cut by the shield clip, the way a bend is. Drawn
    with a real buckle rather than a plain stripe, because the club is named
    for the object, not for the heraldic ordinary."""
    ang = math.radians(-22)
    dx, dy = math.cos(ang), math.sin(ang)
    nx, ny = -dy, dx
    hw, L = 34.0, 250.0

    def at(sx, sy):
        return (cx + dx * sx + nx * sy, cy + dy * sx + ny * sy)

    out = [poly([at(-L, -hw), at(L, -hw), at(L, hw), at(-L, hw)], fill=ink)]
    for sy in (-hw * 0.56, hw * 0.56):        # stitching
        out.append(line(at(-L, sy), at(L, sy), stroke=FIELD, width=5))
    out += [
        poly([at(-46, -hw - 15), at(46, -hw - 15), at(46, hw + 15), at(-46, hw + 15)], fill=hi),
        poly([at(-26, -hw + 3), at(26, -hw + 3), at(26, hw - 3), at(-26, hw - 3)], fill=FIELD),
        line(at(0, -hw + 3), at(0, hw - 3), stroke=hi, width=10),
    ]
    return out


# ── the eight ────────────────────────────────────────────────────────────────
# id, Arabic name, Latin name, accent, silhouette, emblem, and where the emblem
# and the ball sit. The two offsets are per-club because the emblems are
# different heights: one shared layout left the cedar crowding the ball and the
# belt sitting on top of it.

TEAMS = [
    ("an-najihin", "الناجحين", "An-Najihin", "azure",
     lambda d=0: peaked(d), em_summit, 206, 356, 56),
    ("ash-shanaqita", "الشناقطة", "Ash-Shanaqita", "copper",
     lambda d=0: arched(d), em_minaret, 206, 388, 46),
    ("lubnan", "لبنان", "Lubnan", "clinical",
     lambda d=0: heater(d), em_cedar, 190, 378, 50),
    ("as-sadiqin", "الصادقين", "As-Sadiqin", "plum",
     lambda d=0: notched(d), em_true_star, 210, 372, 50),
    ("afjar", "أفجار", "Afjar", "garnet",
     lambda d=0: domed(d), em_dawn, 196, 366, 48),
    ("adh-dhahabiyin", "الذهبيين", "Adh-Dhahabiyin", "sand",
     lambda d=0: heater(d, waist=0.40, tuck=0.70, half=174), em_sun_laurel, 214, 384, 44),
    ("al-barin", "البارين", "Al-Barin", "olive",
     lambda d=0: peaked(d, rise=22), em_palm, 206, 380, 46),
    ("al-hizam", "الحزام", "Al-Hizam", "slate",
     lambda d=0: heater(d, waist=0.46, tuck=0.60, half=174), em_belt, 300, 186, 58),
]


def crest(team):
    tid, ar, fr, accent, shape, emblem, em_y, ball_y, ball_r = team
    hi, soft = ACCENTS[accent]
    outline, keyline = shape(0), shape(19)

    out = [
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">',
        f'  <title>{fr} — {ar}</title>',
        '  <!-- GENERATED by tools/draw/mayor-cup-teams.py. Do not hand-edit. -->',
        '  <defs>',
        f'    <clipPath id="shield"><path d="{outline}"/></clipPath>',
        '  </defs>',
        path(outline, fill=FIELD),
        '  <g clip-path="url(#shield)">',
    ]
    body = [path(keyline, stroke=soft, width=4)]
    body += emblem(CX, em_y, soft, hi)
    body += football(CX, ball_y, ball_r, FIELD, soft)
    out += ["  " + e.strip() for e in body]
    out += [
        '  </g>',
        # the edge goes on last, so a clipped emblem stops against it cleanly
        path(outline, stroke=hi, width=14),
        '</svg>',
    ]
    return "\n".join(out) + "\n"


def main():
    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    out = os.path.join(root, "logos", "src", "teams", EVENT)
    os.makedirs(out, exist_ok=True)
    for t in TEAMS:
        dst = os.path.join(out, f"{t[0]}.svg")
        # REFUSE to overwrite artwork this script did not write. The eight files
        # here were redrawn by hand after this generator produced the first
        # draft, and a generator that silently replaces the real artwork with
        # its own draft is a trap — the tree looks fine until someone runs it.
        if os.path.exists(dst) and MARK not in open(dst, encoding="utf-8").read():
            print(f"SKIP  {t[0]}.svg — hand-drawn, not generated by this script")
            continue
        with open(dst, "w", encoding="utf-8") as fh:
            fh.write(crest(t))
        print(f"wrote logos/src/teams/{EVENT}/{t[0]}.svg  ({t[1]})")


if __name__ == "__main__":
    main()
