#!/usr/bin/env python3
"""
Draws logos/src/glyphs/stethoscope-heart.svg.

    python3 tools/draw/stethoscope.py

The stethoscope is the ORIGINAL drawing, kept coordinate for coordinate: the
binaural U, the two ear crossbars, the tube swinging right, the bell. Only two
things changed, and only because the heart had to become visible.

  1. Figure and ground swapped. The heart used to be filled in the soft tone
     with the stethoscope stroked over it. The soft tone becomes `none` in the
     one-ink variants, so the heart was deleted outright there, and in full
     colour a pale tint on the courtyard's mint is barely a shade, so it did
     not read on the symbol either. Now the heart is the mass and the
     stethoscope is cut out of it. A hole is not a colour, so it survives
     every variant and every ground.
  2. It is scaled to sit inside a heart that fills the box, rather than
     spilling over a smaller one.

Which is why this is generated. Cutting a stroke out of a shape means turning
that stroke into an outline, and two subpaths of one evenodd path CANCEL where
they overlap - the tube would erase the piece of headset it crosses. So every
piece is built to TOUCH its neighbour and never overlap: the tube starts on the
headset's outer edge, the crossbars rest on the arm tops, the tube ends on the
bell's outer radius. Those three joins are derived from the stroke width, not
typed in. Change the numbers under "the original stethoscope" and re-run; do
not hand-edit the path data.
"""
import math, os

def U(v):
    n = math.hypot(*v) or 1.0
    return (v[0]/n, v[1]/n)
def perp(d): return (-d[1], d[0])
def add(a,b): return (a[0]+b[0], a[1]+b[1])
def mul(a,k): return (a[0]*k, a[1]*k)

def offset(pts, h, sign):
    segs=[U((pts[i+1][0]-pts[i][0], pts[i+1][1]-pts[i][1])) for i in range(len(pts)-1)]
    out=[]
    for i,P in enumerate(pts):
        if i==0: nv=perp(segs[0]); m=1.0
        elif i==len(pts)-1: nv=perp(segs[-1]); m=1.0
        else:
            a,b=perp(segs[i-1]), perp(segs[i])
            nv=U(add(a,b)); m=1.0/max(0.35, nv[0]*b[0]+nv[1]*b[1])
        out.append(add(P, mul(nv, sign*h*m)))
    return out

def f(p): return f"{p[0]:.2f},{p[1]:.2f}"

def stroke(pts, h, cap0='flat', cap1='flat'):
    L, R = offset(pts,h,+1), offset(pts,h,-1)
    d=["M "+f(R[0])] + ["L "+f(p) for p in R[1:]]
    d.append(f"A {h:.2f},{h:.2f} 0 0 1 "+f(L[-1]) if cap1=='round' else "L "+f(L[-1]))
    d += ["L "+f(p) for p in reversed(L[:-1])]
    if cap0=='round': d.append(f"A {h:.2f},{h:.2f} 0 0 1 "+f(R[0]))
    d.append("Z")
    return " ".join(d)

def arc(cx,cy,r,a0,a1,n=24):
    return [(cx+r*math.cos(math.radians(a0+(a1-a0)*i/n)),
             cy+r*math.sin(math.radians(a0+(a1-a0)*i/n))) for i in range(n+1)]

def circ(cx,cy,r,hole=True):
    s = "0 1 0" if hole else "0 1 1"
    e = "0.01,0" if hole else "-0.01,0"
    return f"M {cx:.2f},{cy-r:.2f} a {r:.2f},{r:.2f} {s} {e} Z"

# ── the original stethoscope, verbatim from git ──────────────────────────────
#   headset  M35 26 v13 a13 13 0 0 0 26 0 V26
#   eartips  M31 24 h8   M57 24 h8
#   tube     M48 52 v9 a11 11 0 0 0 22 0 v-5
#   bell     circle 70,45 r6            all stroke-width 4  ->  h = 2
S, CX, CY = 0.95, 50.0, 50.0
def T(p): return (CX + (p[0]-53.5)*S, CY + (p[1]-48.0)*S)
H = 2.0                                   # half stroke width, final units

headset = [T(p) for p in [(35,26)] + arc(48,39,13,180,0) + [(61,26)]]
tube_c  = [T(p) for p in [(48,52)] + arc(59,61,11,180,0) + [(70,53)]]
bellC, bellR = T((70,45)), 6*S

# Touch, never overlap: two holes that overlap cancel back to solid.
tube_c[0]  = (tube_c[0][0],  T((48,52))[1] + H)          # onto the headset's outer edge
tube_c[-1] = (tube_c[-1][0], bellC[1] + bellR + H)       # onto the bell's outer edge
cb_y = T((35,26))[1] - H                                  # crossbars rest on the arm tops

parts = [
    stroke(headset, H),
    stroke([(T((29,0))[0], cb_y), (T((41,0))[0], cb_y)], H, 'round', 'round'),
    stroke([(T((57,0))[0], cb_y), (T((69,0))[0], cb_y)], H, 'round', 'round'),
    stroke(tube_c, H),
    circ(*bellC, bellR+H, hole=True), circ(*bellC, bellR-H, hole=False),
]

HEADER = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
  <title>Comité de santé — اللجنة الصحية</title>
  <!-- GENERATED by tools/draw/stethoscope.py. Do not hand-edit the path data. -->
"""

HEART = ("M 50,88 C 20,66 6,51 6,36 C 6,23 16,13 28,13 C 38,13 45,20 50,28 "
         "C 55,20 62,13 72,13 C 84,13 94,23 94,36 C 94,51 80,66 50,88 Z")
out = os.path.join(os.path.dirname(__file__), "..", "..", "logos", "src", "glyphs",
                   "stethoscope-heart.svg")
open(out, "w").write(
    HEADER
    + '  <path fill="var(--glyph, #b0643e)" fill-rule="evenodd" d="\n    '
    + HEART + '\n    ' + "\n    ".join(parts) + '"/>\n</svg>\n')
print("wrote", os.path.relpath(out))
