#!/usr/bin/env node
/**
 * Markdown slides in, PDF/HTML/PPTX out.
 *
 *   content/presentations/<name>.md  ->  dist/presentations/<name>.pdf
 *
 * Marp does the slide mechanics; this script does the one thing Marp cannot.
 *
 * A Marp theme cannot `@import` the token files: relative imports inside a
 * theme are not resolved against the theme's own location, so the import
 * silently fails and the deck renders as unstyled black text on white. Nothing
 * errors — you just get a bad deck. So the theme is assembled here into one
 * self-contained file, with the font URLs made absolute, and Marp is handed
 * that.
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync, rmSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { basename } from 'node:path'
import { p } from './lib/paths.mjs'

const outDir = p('dist/presentations')
const tmpDir = p('dist/.deck-theme')
mkdirSync(outDir, { recursive: true })
mkdirSync(tmpDir, { recursive: true })

// Assemble a standalone theme: the @theme directive must stay on line one.
const theme = readFileSync(p('templates/presentations/theme/ajvt.css'), 'utf8')
const fonts = readFileSync(p('brand/tokens/fonts.css'), 'utf8')
  .replace(/url\("\.\.\/fonts\//g, `url("file://${p('brand/fonts')}/`)
const tokens = readFileSync(p('brand/tokens/tokens.css'), 'utf8')

const assembled = [
  '/* @theme ajvt */',
  '/* GENERATED by tools/build-decks.mjs — do not edit.',
  '   Edit templates/presentations/theme/ajvt.css and rebuild. */',
  fonts,
  tokens,
  theme.replace(/^\/\* @theme ajvt \*\/\s*/, '').replace(/^@import url\([^)]*\);\s*$/gm, ''),
].join('\n\n')

const themeFile = p('dist/.deck-theme/ajvt.css')
writeFileSync(themeFile, assembled)

const src = p('content/presentations')
const decks = existsSync(src) ? readdirSync(src).filter((f) => f.endsWith('.md')) : []
if (!decks.length) console.log('  no decks in content/presentations/ yet')

const formats = process.argv.includes('--pptx') ? ['pdf', 'html', 'pptx'] : ['pdf', 'html']

for (const deck of decks) {
  const name = basename(deck, '.md')
  for (const fmt of formats) {
    execFileSync('npx', [
      'marp', '--allow-local-files', '--theme', themeFile,
      `--${fmt}`, p('content/presentations', deck),
      '-o', p('dist/presentations', `${name}.${fmt}`),
    ], {
      stdio: ['ignore', 'ignore', 'inherit'],
      // Marp otherwise tries to download its own Chromium.
      env: { ...process.env, CHROME_PATH: process.env.CHROME_PATH ?? '/usr/bin/google-chrome' },
    })
  }
  console.log(`  ${name.padEnd(44)} ${formats.join(', ')}`)
}

rmSync(tmpDir, { recursive: true, force: true })
