#!/usr/bin/env node
/**
 * Emits the generated token artefacts. Everything downstream — the document
 * theme, the deck theme, the card templates, the studio — imports one of these
 * rather than hard-coding a value.
 *
 *   brand/tokens/tokens.css   custom properties, for any HTML template
 *   brand/tokens/fonts.css    @font-face for the ACTIVE faces, self-hosted
 *   brand/tokens/tokens.json  the same values resolved, for scripts
 *
 * These three files are generated. Do not edit them; edit color.json,
 * type.json, space.json and rebuild.
 */
import { writeFileSync, readdirSync, existsSync } from 'node:fs'
import { p } from './lib/paths.mjs'
import { loadTokens } from './lib/tokens.mjs'

const t = loadTokens()
const banner = `/* GENERATED by tools/build-tokens.mjs — do not edit.\n   Edit brand/tokens/{color,type,space}.json and run \`npm run build:tokens\`. */\n\n`

/* ── tokens.css ─────────────────────────────────────────────────────────── */
const lines = [':root {']
lines.push('  /* palette */')
for (const [group, steps] of Object.entries(t.color.palette))
  for (const [step, hex] of Object.entries(steps)) lines.push(`  --${group}-${step}: ${hex};`)

lines.push('', '  /* semantic — prefer these in a template */')
for (const [name, hex] of Object.entries(t.semantic)) lines.push(`  --${name}: ${hex};`)

lines.push('', '  /* accents, one per committee */')
for (const [name, tones] of Object.entries(t.accents))
  for (const [tone, hex] of Object.entries(tones)) lines.push(`  --accent-${name}-${tone}: ${hex};`)

lines.push('', '  /* type — resolved from the active switch in type.json */')
for (const [script, roles] of Object.entries(t.fonts))
  for (const [role, face] of Object.entries(roles))
    lines.push(`  --font-${script}-${role}: ${face.stack.map((f) => (f.includes(' ') ? `"${f}"` : f)).join(', ')};`)
lines.push(`  --wordmark-weight-arabic: ${t.fonts.arabic.wordmark['wordmark-weight'] ?? 700};`)
lines.push(`  --wordmark-weight-latin: ${t.fonts.latin.wordmark['wordmark-weight'] ?? 700};`)
lines.push(`  --arabic-size-ratio: ${t.type.pairing?.['arabic-size-ratio'] ?? 1};`)

lines.push('', '  /* scale */')
for (const [k, v] of Object.entries(t.type.scale)) lines.push(`  --text-${k}: ${v};`)
for (const [k, v] of Object.entries(t.type.leading)) lines.push(`  --leading-${k}: ${v};`)

lines.push('', '  /* space */')
for (const [k, v] of Object.entries(t.space.space)) lines.push(`  --space-${k}: ${v};`)
for (const [k, v] of Object.entries(t.space.radius)) lines.push(`  --radius-${k}: ${v};`)
lines.push('}')
writeFileSync(p('brand/tokens/tokens.css'), banner + lines.join('\n') + '\n')

/* ── fonts.css ──────────────────────────────────────────────────────────── */
const faces = []
const seenFace = new Set()
for (const roles of Object.values(t.fonts)) {
  for (const face of Object.values(roles)) {
    if (seenFace.has(face.key)) continue
    seenFace.add(face.key)
    const dir = p('brand/fonts', face.key)
    if (!existsSync(dir)) { console.warn(`  ! ${face.family} not vendored — run \`npm run fonts:fetch\``); continue }
    for (const file of readdirSync(dir).filter((f) => f.endsWith('.ttf'))) {
      const variable = file.includes('[')
      const weight = variable
        ? `${Math.min(...(face.weights ?? [400]))} ${Math.max(...(face.weights ?? [700]))}`
        : String(weightOf(file, face))
      faces.push(
        `@font-face {\n  font-family: "${face.family}";\n  src: url("../fonts/${face.key}/${encodeURI(file)}") format("truetype");\n  font-weight: ${weight};\n  font-style: normal;\n  font-display: block;\n}`
      )
    }
  }
}
writeFileSync(p('brand/tokens/fonts.css'), banner + faces.join('\n\n') + '\n')

function weightOf(file, face) {
  const named = { Thin: 100, ExtraLight: 200, Light: 300, Regular: 400, Medium: 500,
                  SemiBold: 600, Bold: 700, ExtraBold: 800, Black: 900 }
  for (const [name, w] of Object.entries(named)) if (file.includes(`-${name}.`)) return w
  return 400
}

/* ── tokens.json ────────────────────────────────────────────────────────── */
writeFileSync(p('brand/tokens/tokens.json'), JSON.stringify({
  semantic: t.semantic, palette: t.color.palette, accents: t.accents,
  fonts: Object.fromEntries(Object.entries(t.fonts).map(([s, r]) =>
    [s, Object.fromEntries(Object.entries(r).map(([role, f]) => [role, { key: f.key, family: f.family, stack: f.stack }]))])),
  scale: t.type.scale, space: t.space.space, page: t.space.page, logo: t.space.logo,
}, null, 2) + '\n')

console.log(`tokens.css   ${lines.length} declarations`)
console.log(`fonts.css    ${faces.length} @font-face rules`)
console.log(`tokens.json  written`)
